name = "synthetic-blog"
main = ".vercel/output/static/_worker.js"
compatibility_date = "2024-11-19"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".vercel/output/static"
binding = "ASSETS"
